/*
 * @Description: 
 * @Autor: 24
 * @Date: 2021-12-27 17:58:58
 * @LastEditors: 24
 * @LastEditTime: 2022-01-14 09:58:15
 * 
//  /about
 */
import { NextPage } from 'next';
import Head from 'next/head'
import styles from './Home.module.css';


// req, res
const Home: NextPage = ({ stars }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {stars}
      </main>
    </div>
  )
}

Home.getInitialProps = async (_ctx) => {
  const res = await fetch('https://api.github.com/repos/vercel/next.js')
  const rjson = await res.json();
  return { stars: JSON.stringify(rjson) }
}

export default Home
