/*
 * @Description: 
 * @Autor: 24
 * @Date: 2021-12-27 17:58:58
 * @LastEditors: 24
 * @LastEditTime: 2022-01-21 17:54:45
 * 
//  /about
 */
import { NextPage } from 'next';
import Head from 'next/head';
import { Button } from 'antd';
import {  useEffect } from 'react';
import styles from './Home.module.less';

import { defaultApi } from '../server/defaultApi';

// req, res
const Home: NextPage  = () => {

  useEffect(() => {
    getData();
  },[])

  const getData = async () => {
    const res = await defaultApi();
    console.log('页面res--------->', res)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button type='primary'>12121</Button>
      <main className={styles.main}>
      
      </main>
    </div>
  )
}

Home.getInitialProps = async (_ctx) => {
  const res = await fetch('https://api.github.com/repos/vercel/next.js')
  const rjson = await res.json();
  return { stars: JSON.stringify(rjson) }
}

export default Home
